evalTime = 500
popSize = 10
numGens = 20
numEnvs = 10
vectorized_mutation = True
mutRate = 30    # Expressed as a percentage
elitismRate = 50  # Expressed as a percentage
fitnessMetric = 'best_keeper'  # string: goals_scored, distance_travelled, best_keeper, reward_efforts
randomSeed = 42  # integer
